@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class anwendungsfall {
   anwendungsfalllang: varchar
   gueltig_ab: date
   gueltig_bis: date
   typen: bit varying
   messart: integer
   anwendungsfall_metaname: varchar(25)
   show_puenkt_einzel: boolean
   id_mvu: varchar(10)
   ranking_wichtung_obj: numeric
   ranking_wichtung_subj: numeric
   color: char(7)
   afz: boolean
   id_anwendungsfall: varchar(5)
}
class bhf {
   id_anwendungsfall: varchar(4)
   id_bhf: varchar
   bahnhof: varchar
   import_date: date
   qmt_messung: numeric(1)
   quelle: integer
   typ: integer[]
   koord_x: numeric
   koord_y: numeric
   koord_z: numeric
   abkuerzung: varchar(10)
   id_t_kanton: integer
   gueltigkeit: daterange
   go_nr: integer
   gemeinde: varchar(40)
   id_t_bhf: integer
}
class import {
   id_anwendungsfall: char(4)
   beschreibg: varchar(500)
   import_typ: integer
   import_time: timestamp
   datpfad: varchar(500)
   datname: varchar(500)
   status: integer
   daten_von: date
   daten_bis: date
   freischaltung: integer
   vorberechnet: boolean
   quelle: integer
   id_mvu: varchar(10)
   status_pruefung: integer
   bemerkung: text
   anschluss_vorberechnet: boolean
   username: varchar(500)
   fpl_id_t_import: integer
   gonr: integer
   id_t_import: integer
}
class kanton {
   id_kanton: varchar(5)
   kanton_kurz: varchar
   kanton_lang: varchar(150)
   geom: geometry
   id_t_kanton: integer
}
class linie {
   id_anwendungsfall: varchar(4)
   id_linie: varchar
   linie: varchar(200)
   linie_produkt: integer
   liniebemerkg: varchar(200)
   id_mvu: varchar(10)
   typ: integer
   gueltigkeit: daterange
   linienlaenge: numeric(7,3)
   fahrtkm_projahr: numeric(10,3)
   personenkm_projahr: numeric(15,3)
   kurspaare_projahr_mofr: text
   kurspaare_projahr_sa: text
   kurspaare_projahr_so: text
   id_mvu_gefahren: varchar(10)
   messart: integer
   produkt_detail: integer
   dpmtool_ignore: boolean
   id_vmkat: integer
   id_t_linie: integer
}
class linie_lb {
   id_t_linie: integer
   id_t_lb: integer
   gueltigkeit: daterange
   id_t_linie_lb: integer
}
class linienbuendel {
   id_lb: varchar(4)
   lb_kurz: varchar(20)
   lb_lang: varchar(50)
   id_anwendungsfall: varchar(4)
   id_vmkat: integer
   gueltigkeit: daterange
   id_t_lb: integer
}
class mvu {
   mvulang: varchar(50)
   webservice_pin: varchar(10)
   verkehrsmitteltyp: integer[]
   mss_web: boolean
   mss_mda: boolean
   dpm_web: boolean
   status: integer
   dpm_log_email: text
   dpm_log_email_absender: boolean
   zustaendigkeitsbereiche_ausschluss: text
   foto: bytea
   lnp_datei: bytea
   kontaktpersonen: text
   id_mvu: varchar(10)
}
class puenkt {
   id_t_import: integer
   id_anwendungsfall: varchar(4)
   id_mvu: varchar(10)
   id_linie_tu: varchar(10)
   id_fahrt: varchar(20)
   betriebstag: date
   fahrt_halt_lauf: integer
   id_messpunkt: integer
   id_an_ab: integer
   soll_bav: timestamp
   soll_tu: timestamp
   ist_tu: timestamp
   id_verspcode: varchar(10)
   insert_time: timestamp
   id_t_linie_bav: integer
   qrelevant: boolean
   go_nr: integer
   id_t_puenkt_fahrt: integer
   manipulation_time: timestamp
   id_fahrt_tu: varchar(20)
   id_t_puenkt: bigint
}
class puenkt_fahrt {
   id_t_import: integer
   id_anwendungsfall: varchar(4)
   betriebstag: date
   id_mvu: varchar(10)
   go_nr: integer
   id_fahrt: varchar(50)
   id_fahrt_differentiator: smallint
   id_fahrt_tu: varchar(50)
   direction_id: smallint
   fahrzeugtyp: varchar(10)
   id_t_puenkt_fahrt: integer
}
class puenkt_kat {
   id_anwendungsfall: varchar(4)
   puenkt_kat: integer
   move_type: varchar
   id_t_puenktkat: integer
}
class v_dpm_vorberechnet_neu {
   puenkt_kat: integer
   id_t_import: integer
   id_anwendungsfall: varchar(4)
   id_mvu: varchar(10)
   id_linie_tu: varchar(10)
   betriebstag: date
   id_messpunkt: integer
   id_an_ab: integer
   id_t_linie_bav: integer
   qrelevant: boolean
   id_verspcode: varchar(10)
   anz_puenkt_tu: bigint
   anz_puenkt_bav: bigint
   anz_mess_tu: bigint
   anz_mess_bav: bigint
   go_nr: integer
   id_t_lb: integer
   direction_id: smallint
}
class verkehrsmittel_kategorie {
   vmkat_kurz: varchar(25)
   vmkat_lang: varchar(50)
   id_verkehrstraeger: integer
   vmkat_kurz_fr: varchar(25)
   vmkat_lang_fr: varchar(50)
   vmkat_kurz_it: varchar(25)
   vmkat_lang_it: varchar(50)
   lang_key: varchar(100)
   id_anwendungsfall: varchar(4)
   id_vmkat: integer
}
class verkehrstraeger {
   id_verkehrstraeger: integer
   vt_sprach_key_kurz: varchar(20)
   vt_sprach_key_lang: varchar(100)
   id_t_verkehrstraeger: integer
}

bhf                       -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
bhf                       -[#595959,plain]-^  kanton                   : "id_t_kanton"
import                    -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
import                    -[#595959,plain]-^  mvu                      : "id_mvu"
linie                     -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
linie                     -[#595959,plain]-^  mvu                      : "id_mvu"
linie                     -[#595959,plain]-^  verkehrsmittel_kategorie : "id_anwendungsfall, id_vmkat"
linie_lb                  -[#595959,plain]-^  linie                    : "id_t_linie"
linie_lb                  -[#595959,plain]-^  linienbuendel            : "id_t_lb"
linienbuendel             -[#595959,plain]-^  verkehrsmittel_kategorie : "id_anwendungsfall, id_vmkat"
puenkt                    -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
puenkt                    -[#595959,plain]-^  bhf                      : "id_messpunkt:id_t_bhf"
puenkt                    -[#595959,plain]-^  import                   : "id_t_import"
puenkt                    -[#595959,plain]-^  linie                    : "id_t_linie_bav:id_t_linie"
puenkt                    -[#595959,plain]-^  mvu                      : "id_mvu"
puenkt_fahrt              -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
puenkt_fahrt              -[#595959,plain]-^  import                   : "id_t_import"
puenkt_fahrt              -[#595959,plain]-^  mvu                      : "id_mvu"
puenkt_kat                -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
verkehrsmittel_kategorie  -[#595959,plain]-^  anwendungsfall           : "id_anwendungsfall"
verkehrsmittel_kategorie  -[#595959,plain]-^  verkehrstraeger          : "id_verkehrstraeger"
@enduml
