create table puenkt
(
    id_t_puenkt       bigint generated by default as identity
        constraint pk_puenkt
            primary key,
    id_t_import       integer                         not null
        constraint fk_puenkt_import
            references import
            on update cascade on delete cascade,
    id_anwendungsfall varchar(4)                      not null
        constraint fk_puenkt_anw
            references anwendungsfall
            on delete restrict,
    id_mvu            varchar(10)                     not null
        constraint fk_puenkt_mvu
            references mvu
            on update cascade,
    id_linie_tu       varchar(10)                     not null,
    id_fahrt          varchar(20)                     not null,
    betriebstag       date                            not null,
    fahrt_halt_lauf   integer   default '-1'::integer not null,
    id_messpunkt      integer                         not null
        constraint fk_puenkt_bhf
            references bhf
            on update cascade,
    id_an_ab          integer                         not null,
    soll_bav          timestamp,
    soll_tu           timestamp                       not null,
    ist_tu            timestamp                       not null,
    id_verspcode      varchar(10),
    insert_time       timestamp default now(),
    id_t_linie_bav    integer
        references linie
            on update cascade on delete restrict,
    qrelevant         boolean   default false         not null,
    go_nr             integer   default '-1'::integer not null,
    id_t_puenkt_fahrt integer,
    manipulation_time timestamp,
    id_fahrt_tu       varchar(20),
    last_update       date,
    constraint uk_puenkt
        unique (id_anwendungsfall, id_mvu, go_nr, id_t_linie_bav, betriebstag, id_fahrt, fahrt_halt_lauf, id_messpunkt,
                id_an_ab)
);

create index idx_puenkt_auswertung2
    on puenkt (betriebstag)
    where (id_t_linie_bav IS NOT NULL);

create index idx_puenkt_auswertung_uhrzeit_bav
    on puenkt (soll_bav)
    where (soll_bav IS NOT NULL);

create index idx_puenkt_anwendungsfall
    on puenkt (id_anwendungsfall);

create index idx_puenkt_auswertung_uhrzeit_tu
    on puenkt ((soll_tu::time without time zone));

create index idx_puenkt_dpmrecherche
    on puenkt (betriebstag, id_mvu, id_fahrt);

create index idx_puenkt_zugnummer
    on puenkt (id_anwendungsfall, id_fahrt text_pattern_ops);

create index idx_puenkt_idtimport
    on puenkt (id_t_import);

create index idx_puenkt_idtliniebav
    on puenkt (id_t_linie_bav);

create index idx_puenkt_messpunkt
    on puenkt (id_messpunkt);

create index idx_puenkt_rohdatenanzeige
    on puenkt (betriebstag, id_mvu);

create index idx_puenkt_rohdatenanzeige_3
    on puenkt (betriebstag, id_mvu, qrelevant, id_t_linie_bav);

create index idx_betriebstag_id_t_linie_bav_id_fahrt
    on puenkt (betriebstag, id_t_linie_bav, id_fahrt);

create index idx_puenkt_rohdatenanzeige_2
    on puenkt (betriebstag, id_mvu, id_linie_tu);

create index idx_puenkt_sollupdate
    on puenkt (id_t_import, betriebstag)
    where (soll_bav IS NULL);

